# Site
title:              Leop0ld
bio:                "Leop0ld! Personal Tech Blog."
description:        "Keep Calm and Code Python and JavaScript."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/profile_image.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://leop0ld.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-leop0ld-github-io

# Social
email:              l3pold7@gmail.com
twitter:            leop0ld7
facebook:           leop0ld
github:             Leop0ld
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
instagram:          myungseokang
codepen:            Leop0ld

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: "https://github.com"

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
