# Site settings
email: l3opold7@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-84594819-1

# SEO settings
title: Leop0ld
description: Leop0ld's Personal Tech Blog!
url: ""
twitter_username: __leop0ld__
default_img: 

# Profile settings
name: Myungseo Kang
profile_img: 
profile: Web Developer / Djangogirls Seoul Organizer
social:
  github: https://github.com/Leop0ld
  facebook: https://fb.me/leop0ld
  instagram: https://instagram.com/myungseokang
  linkedin: https://linkedin.com/in/leop0ld
  codepen: https://codepen.io/Leop0ld


# Build settings
include: ["_categories"]
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
