# Site wide configuration

title: Myungseo Kang
locale: ko_KR
description: DEV Blog
logo: profile.jpg
search: true
url: https://blog.myungseokang.space

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Myungseo Kang
  avatar: profile.jpg
  email: iam@myungseokang.dev
  twitter: myungseokang
  facebook: myungseokang7
  github: myungseokang
  stackexchange: https://stackoverflow.com/users/5506957/leop0ld
  linkedin: myungseokang
  instagram: __myungseokang__
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-84594819-1
    verify:
    ad-client: ca-pub-1864899826477546
    ad-slot: 8540897902
  bing-verify:
