# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from

# Site settings
title: "Leop0ld"
description: "Personal TECH Blog!"
email: "l3op0ld7@gmail.com"
#blog logo
logo: "/assets/img/profile.jpg"
# blog cover
cover: "/assets/img/cover.jpg"

authors:
  leop0ld:
    name: Myungseo Kang
    image: /assets/img/profile.jpg

paginate: 10

url: "http://leop0ld.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@__leop0ld__'

#fill in disqus shortname to use disqus
disqus: 'https-leop0ld-github-io'

timezone: Asia/Seoul

# social icons and sharing options
social:

  - icon: facebook
    url: http://fb.me/leop0ld
    desc: Leop0ld's facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: "?t="
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/Leop0ld
    desc: Leop0ld's GitHub
    share_url:
    share_title:
    share_link:

  - icon: twitter
    url:  https://twitter.com/__leop0ld__
    desc: Leop0ld's Twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="
